name: danidani/casehome
typeName: danidani_casehome
group: default
prefixFields: true
prefixType: full
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  - identifier: header
    useExistingField: true
    label: 'Header (yes, it is rendered in Frontend)'
  - identifier: checkboxes
    type: Checkbox
    label: 'Text white? (default black)'
    required: false
  - identifier: image
    useExistingField: true
    type: File
    extendedPalette: true
    allowed: common-image-types
    required: false
    label: 'Added more images, as one of them will automatically create a slider'
  - identifier: url
    type: Link
    label: 'Add a link to the matching subpage'
    autocomplete: true
    allowedTypes:
      - page
      - url
      - file
      - news
    required: false
  - identifier: text
    type: Text
    label: 'Direct link from vimeo'
    default: 'Direct link to the movie from vimeo (only direct link will work)'
    required: false
  - identifier: checkboxio
    type: Checkbox
    label: 'Main Video?'
    required: false
